version: 0.0
os: windows
files:
  - source: \
    destination: c:\inetpub\wwwroot\PollWebFrontend
hooks:
  ApplicationStop:
    - location: .\approot\src\PollWebFrontend\CodeDeployScripts\IIS_RemoveWebApp.ps1
      timeout: 30
  ApplicationStart:
    - location: .\approot\src\PollWebFrontend\CodeDeployScripts\IIS_SetupWebApp.ps1
      timeout: 30